x-function: &base_python
  volumes:
    - ./:/app/:rw  
    - poetry-volume:/poetry:delegated
  environment: &env-vars
    POETRY_HOME: /poetry
    PYTHONPATH: /app
    SECRET_KEY: ${SECRET_KEY}
    DEBUG: ${DEBUG}
    DB_HOST: ${DB_HOST}
    DB_NAME: ${DB_NAME}
    DB_USER: ${DB_USER}
    DB_PASS: ${DB_PASSWORD}
  depends_on:
    - db
  env_file:
    - .env
  networks:
    - internal

x-celery: &base_celery
  <<: *base_python
  build:
    context: .
    dockerfile: web.dockerfile
  entrypoint: celery
  restart: on-failure

services:
  db:
    container_name: ${PROJECT_NAME}_db
    image: postgres:14.6-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata:rw
    env_file:
      - .env
    networks:
      - internal
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata

  nginx:
    build: ./nginx
    container_name: ${PROJECT_NAME}_nginx
    volumes:
      - static_dir:/app/web/static/  
      - media_dir:/app/web/media/ 
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - internal

  web:
    <<: *base_python
    build:
      context: .
      dockerfile: web.dockerfile
    container_name: ${PROJECT_NAME}_web
    volumes:
      - ./:/app/:rw
      - poetry-volume:/poetry:delegated
      - static_dir:/app/web/static/  
      - media_dir:/app/web/media/ 

  bot:
    <<: *base_python
    build:
      context: .
      dockerfile: bot.dockerfile
    container_name: ${PROJECT_NAME}_bot
    command: python bot/reloader.py

  redis:
    image: redis:7.0.11-alpine
    hostname: redis
    container_name: ${PROJECT_NAME}_redis
    volumes:
      - redis_data:/data
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    networks:
      - internal
    env_file:
      - .env
    restart: on-failure

  scheduler:
    <<: *base_celery
    hostname: scheduler
    container_name: ${PROJECT_NAME}_scheduler
    command: -A web.core.celery_init beat -l debug

  worker:
    <<: *base_celery
    hostname: worker
    container_name: ${PROJECT_NAME}_worker
    command: >
      -A web.core.celery_init worker -l info 

volumes:
  static_dir:
  media_dir:
  pg_data:
  poetry-volume:
  redis_data:

networks:
  internal: