# Generated by Django 4.2.1 on 2026-06-20 10:01

from django.db import migrations, models
import django.db.models.deletion
import web.db.model_mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('telegram_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.CharField(db_index=True, default=web.db.model_mixins.ulid_default, editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна ли подписка')),
                ('start_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата начала подписки')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания подписки')),
                ('telegram_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='telegram_users.telegramuser', verbose_name='Пользователь Telegram')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
    ]
