# Generated by Django 4.2.1 on 2026-07-25 08:21

from django.db import migrations, models
import django.db.models.deletion
import web.db.model_mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('telegram_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateChannelTariff',
            fields=[
                ('id', models.CharField(db_index=True, default=web.db.model_mixins.ulid_default, editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('title', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=8, max_digits=10, verbose_name='Цена')),
                ('term_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Срок в днях')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.CharField(db_index=True, default=web.db.model_mixins.ulid_default, editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активна ли подписка')),
                ('start_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата начала подписки')),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата окончания подписки')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='subscription', to='payments.payment', verbose_name='Платеж')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.privatechanneltariff', verbose_name='Тариф')),
                ('telegram_user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription', to='telegram_users.telegramuser', verbose_name='Пользователь Telegram')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
    ]
