# Generated by Django 4.2.1 on 2026-07-26 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='privatechanneltariff',
            options={'verbose_name': 'Тариф доступа в приватку', 'verbose_name_plural': 'Тарифы доступа в приватку'},
        ),
    ]
