# Generated by Django 4.2.1 on 2026-07-26 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_users', '0001_initial'),
        ('subscriptions', '0002_alter_privatechanneltariff_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='telegram_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription', to='telegram_users.telegramuser', verbose_name='Пользователь Telegram'),
        ),
    ]
