# Generated by Django 4.2.1 on 2026-07-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_subscription_telegram_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='invite_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
