# Generated by Django 4.2.1 on 2026-07-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_subscription_invite_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='is_invite_link_sent',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
