# Generated by Django 4.2.1 on 2026-07-27 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_subscription_is_invite_link_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='invite_link',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
