# Generated by Django 4.2.1 on 2026-07-28 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_alter_subscription_invite_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='invite_link',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='is_invite_link_sent',
        ),
    ]
