# Generated by Django 4.2.1 on 2026-07-30 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_users', '0003_telegramuser_telegram_us_telegra_9cdf2f_idx'),
        ('subscriptions', '0007_remove_subscription_invite_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='telegram_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='telegram_users.telegramuser', verbose_name='Пользователь Telegram'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['telegram_user', 'is_active'], name='subscriptio_telegra_fd4fa3_idx'),
        ),
    ]
