upstream django {
    server web:8000;
}

server {
    listen 80;
    server_name martin-private.duckdns.org;

    return 301 https://$host$request_uri;
}


server {
    listen 443 ssl;
    server_name martin-private.duckdns.org;

    ssl_certificate
        /etc/letsencrypt/live/mybot.duckdns.org/fullchain.pem;
    ssl_certificate_key
        /etc/letsencrypt/live/mybot.duckdns.org/privkey.pem;


    location / {
        proxy_pass http://django;
        include proxy_params;
    }


    location /static/ {
        alias /app/web/static/;
    }


    location /media/ {
        alias /app/web/media/;
    }
}