# Generated by Django 4.2.1 on 2026-07-25 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('telegram_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='face_rate', to='payments.payment', verbose_name='Платеж,')),
            ],
            options={
                'verbose_name': 'Рейт',
                'verbose_name_plural': 'Рейты',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='FaceRateTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('title', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FaceRatePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фото')),
                ('face_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='face_rates.facerate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='facerate',
            name='tariff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='face_rates', to='face_rates.faceratetariff', verbose_name='Тариф'),
        ),
        migrations.AddField(
            model_name='facerate',
            name='telegram_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_rates', to='telegram_users.telegramuser', verbose_name='Пользователь Telegram'),
        ),
    ]
