# Generated by Django 4.2.1 on 2026-07-26 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face_rates', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faceratetariff',
            options={'verbose_name': 'Тариф', 'verbose_name_plural': 'Тарифы'},
        ),
    ]
