# Generated by Django 4.2.1 on 2026-07-25 07:35

from django.db import migrations, models
import web.db.model_mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.CharField(db_index=True, default=web.db.model_mixins.ulid_default, editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True, verbose_name='Телеграм ID')),
                ('username', models.CharField(db_index=True, max_length=70, null=True, unique=True, verbose_name='Имя пользователя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Фамилия')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
