# Generated by Django 4.2.1 on 2026-07-30 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='has_channel_access',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
