# Generated by Django 4.2.1 on 2026-07-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_users', '0002_telegramuser_has_channel_access'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='telegramuser',
            index=models.Index(fields=['telegram_id', 'has_channel_access'], name='telegram_us_telegra_9cdf2f_idx'),
        ),
    ]
