# Generated by Django 4.2.1 on 2026-07-25 07:25

from django.db import migrations, models
import web.db.model_mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateChannelTariff',
            fields=[
                ('id', models.CharField(db_index=True, default=web.db.model_mixins.ulid_default, editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('info_text', models.TextField()),
                ('price', models.DecimalField(decimal_places=6, max_digits=16, verbose_name='Цена')),
                ('term_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Срок в днях')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
