# Generated by Django 4.2.1 on 2026-07-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Сумма')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Метаданные')),
                ('product_type', models.CharField(choices=[('face_rate', 'Рейт лица'), ('private_channel', 'Доступ в приватку'), ('consultation', 'Консультация')], db_index=True, max_length=25, verbose_name='Тип покупки')),
                ('merchant_type', models.CharField(choices=[('crypto_bot', 'CryptoBot'), ('ykassa', 'ЮKassa'), ('starts', 'Telegram Stars')], db_index=True, max_length=20, verbose_name='Мерчант')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-created_at'],
            },
        ),
    ]
