# Generated by Django 4.2.1 on 2026-07-25 08:21

from django.db import migrations, models
import web.db.model_mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.CharField(db_index=True, default=web.db.model_mixins.ulid_default, editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=10, verbose_name='Сумма')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Метаданные')),
                ('product_type', models.CharField(choices=[('Face Rate', 'Face Rate'), ('Private Channel Access', 'Private Channel Access'), ('Consultation', 'Consultation')], db_index=True, max_length=25, verbose_name='Тип покупки')),
                ('merchant_type', models.CharField(choices=[('CryptoBot', 'Crypto Bot'), ('ЮKassa', 'Ykassa'), ('Telegram Stars', 'Stars')], db_index=True, max_length=20, verbose_name='Мерчант')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-created_at'],
            },
        ),
    ]
