# Generated by Django 4.2.1 on 2026-07-26 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payload',
            new_name='merchant_payload',
        ),
        migrations.AddField(
            model_name='payment',
            name='merchant_payment_id',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='ID Платежа мерчанта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает оплаты'), ('success', 'Успешно'), ('failed', 'Ошибка'), ('expired', 'Истек'), ('canceled', 'Отменен')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='merchant_type',
            field=models.CharField(choices=[('crypto-bot', 'USDT (CryptoBot)'), ('ykassa', 'Банковской Картой (ЮKassa)')], db_index=True, max_length=20, verbose_name='Мерчант'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='product_type',
            field=models.CharField(choices=[('face-rate', 'Рейт лица'), ('private-channel', 'Доступ в приватку'), ('consultation', 'Консультация')], db_index=True, max_length=25, verbose_name='Тип покупки'),
        ),
        migrations.CreateModel(
            name='ProcessedCryptoBotWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_id', models.BigIntegerField(db_index=True, unique=True)),
                ('update_type', models.CharField(max_length=50)),
                ('request_date', models.DateTimeField(db_index=True)),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.payment')),
            ],
        ),
    ]
