# Generated by Django 4.2.1 on 2026-07-26 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_rename_payload_payment_merchant_payload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='merchant_payment_id',
            field=models.CharField(db_index=True, default=None, max_length=100, null=True, unique=True, verbose_name='ID Платежа мерчанта'),
        ),
    ]
