# Generated by Django 4.2.1 on 2026-07-27 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_merchant_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='invoice_message_id',
            field=models.IntegerField(default=None, null=True, verbose_name='ID сообщения платежа'),
        ),
    ]
