# Generated by Django 4.2.1 on 2026-07-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payment_invoice_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='invoice_message_id',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='ID сообщения платежа'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='merchant_payment_id',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=100, null=True, unique=True, verbose_name='ID Платежа мерчанта'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает оплаты'), ('success', 'Успешно'), ('expired', 'Истек'), ('canceled', 'Отменен')], db_index=True, default='pending', max_length=20),
        ),
    ]
