# Generated by Django 4.2.1 on 2026-07-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_payment_invoice_message_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='expires_at',
            field=models.DateTimeField(db_index=True),
            preserve_default=False,
        ),
    ]
