# Generated by Django 4.2.1 on 2026-07-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_payment_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='expires_at',
            field=models.DateTimeField(db_index=True, verbose_name='Истекает'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает оплаты'), ('success', 'Успешно'), ('expired', 'Истек'), ('canceled', 'Отменен')], db_index=True, default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.DeleteModel(
            name='ProcessedCryptoBotWebhook',
        ),
    ]
