# Generated by Django 4.2.1 on 2026-07-30 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_alter_payment_expires_at_alter_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='product_type',
            field=models.CharField(choices=[('private-channel', '🔐 Доступ в приватку'), ('face-rate', '🗿📐 Рейт лица'), ('consultation', '🧠👨\u200d💻 Консультация')], db_index=True, max_length=25, verbose_name='Тип покупки'),
        ),
    ]
