# Generated by Django 4.2.1 on 2026-08-01 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_alter_payment_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='product_type',
            field=models.CharField(choices=[('private-channel', '🔐 Доступ в приватку'), ('face-rate', '🗿📐 Рейт лица'), ('consultation', '🧠👨\u200d💻 Личная работа или связь с мартином (дорого!)')], db_index=True, max_length=25, verbose_name='Тип покупки'),
        ),
    ]
