# Generated by Django 4.2.1 on 2026-07-25 08:08

from django.db import migrations, models
import django.db.models.deletion
import web.db.model_mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('telegram_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceRate',
            fields=[
                ('id', models.CharField(db_index=True, default=web.db.model_mixins.ulid_default, editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('title', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=8, max_digits=10, verbose_name='Цена')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='face_rate', to='payments.payment', verbose_name='Платеж,')),
                ('telegram_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_ratings', to='telegram_users.telegramuser', verbose_name='Пользователь Telegram')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FaceRatePhoto',
            fields=[
                ('id', models.CharField(db_index=True, default=web.db.model_mixins.ulid_default, editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('photo', models.ImageField(upload_to='', verbose_name='Фото')),
                ('face_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='face_ratings.facerate')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
